# Main Config File Format for Sceptre Power Simulations Pipeline
samples:
  test_data:
    interim: 2

simulate_guide_assignments:
  num_cells_per_pert: [50, 75, 100, 150, 250, 500, 750, 1000, 1400, 1800, 2500, 4000, 7500, 10000]
  num_guides_per_pert: 15
  
fit_dispersions:
  size_factors: "poscounts"
  fit_type: "parametric"
  disp_type: "dispersion"
  
split_target_response_pairs:
  batches: 14 # should be <= len(num_cells_per_pert)
  
sceptre_power_analysis:
  effect_size: 0.15
  reps: 20
  guide_sd: 0.13

compute_power_from_simulations:
  pval_adj_thresh: 0.1