# Main Config File Format for Sceptre Power Simulations Pipeline
samples:
  test_data:
    interim: 2

simulate_guide_assignments:
  num_cells_per_pert: [100, 200, 500, 1000, 2000]
  num_guides_per_pert: 15
  
fit_dispersions:
  size_factors: "poscounts"
  fit_type: "parametric"
  disp_type: "dispersion"
  
split_target_response_pairs:
  batches: 5 # should be <= len(num_cells_per_pert)
  
sceptre_power_analysis:
  effect_size: 0.25 
  reps: 20
  guide_sd: 0.13
