# Main Config File Format for Sceptre-based Power Simulations Pipeline
samples:
  test_data

simulate_guide_assignments:
  num_cells_per_pert: [1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000] 
  
sceptre_power_analysis:
  effect_size: 0.40
  reps: 200

compute_power_from_simulations:
  pval_adj_thresh: 0.1
  positive_proportion: 0.05
  
visualize_power_results:
  tpm_per_gene: NULL
  gene_format: "ensembl"
